### ISSUE TITLE
Delay bug 

### ISSUE THREAD

**Issue by UzumakiYT** [btk5h/skript-mirror#62] opened 2018-06-02 11:05 UTC
**Describe the bug**
if there are two players online only one will get two times "test"

**To reproduce**
`effect testing %player%:	
	trigger:
		wait 1 seconds
		send "TEST" to expression-1	
		
command teste:
	trigger:				
		loop all players:
			testing loop-player`

**Server information**
- skript-mirror: 
- Skript: dev27
- Spigot 1.8.8

**Comment by btk5h** [comment] 2018-06-02 16:28
Duplicate of #61

**Closed by btk5h** 2018-06-02 16:28 UTC
Labels: duplicate
