### ISSUE TITLE
[Feature request] Suppress errors/warning from imports

### ISSUE THREAD

**Issue by andrei923** [btk5h/skript-mirror#118] opened 2019-01-29 17:11 UTC
**Is your feature request related to a problem? Please describe.**
is not really a problem, but may be useful when you want a feature for your skript to be optional.

**Describe the solution you'd like**
to hide error/warning

**Describe alternatives you've considered**

```
import:
	try me.clip.placeholderapi.PlaceholderAPI
```

**Comment by Snow-Pyon** [comment] 2019-01-30 02:59
Duplicate of #104

**Comment by btk5h** [comment] 2019-02-01 05:21
Duplicate of #104

**Closed as completed by btk5h** 2019-02-01 05:21 UTC
Labels: duplicate
